# Generated by Django 3.2.9 on 2021-11-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('genre', models.CharField(max_length=255)),
                ('produser', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('img', models.ImageField(blank=True, null=True, upload_to='main')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('views_count', models.IntegerField(default=0)),
                ('is_publicated', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'фильм',
                'verbose_name_plural': 'Фильмы',
                'ordering': ['name'],
            },
        ),
    ]
